baseURL = "https://jetztinbonn.de"
languageCode = "de-DE"
title = "#JetztInBonn"
theme = "ananke"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "/images/PrelimLogo.png"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 4

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Anja-Pe"